# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.define "ubuntu18_04" #название вм 
  config.vm.box = "ubuntu/bionic64" #образ с https://app.vagrantup.com/
  config.vm.box_check_update = false
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vb|
  config.vm.provision "file", source: "/home/timur/file/file_for_vagrant1", destination: "~/home"
  vb.name = "ubuntu18_04"

  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y python3 python3-pip postgresql postgresql-contrib libpq-dev
  pip3 install django psycopg2-binary
  SHELL
  end
end
